# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 123c19ac2e40b35fca0fed9b5f0a9cc33bba103f6eca66c3fd9871c5e1d5a277634253ae0cbd5e1851efa4b38bb323a001b06ec89d9bb9f37bc789e25adffb73

test:
  secret_key_base: 7df20f63be3929e24d45cbf675a648d8bea3a8ffe3ecd06a1d29f9e095369f4fd9c10df0ed227b185016ad63ea80e534206d40f35327cd7036b90eecc89bbf81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
